s = "Hello, World"
print(s.upper())
print(s.lower())
print(s.capitalize())
print("hello world foo".title())
print("AbC".swapcase())
print("hello".find("l"))
print("hello".rfind("l"))
print("hello".index("l"))
print("hello".rindex("l"))
print("hello".count("l"))
print("hello".count("l", 3))
print("hello".startswith("he"))
print("hello".endswith("lo"))
print("hello".startswith(("x", "he")))
print("a,b,c".split(","))
print("a b  c".split())
print("a,b,c".rsplit(",", 1))
print("a|b|c".split("|", 1))
print(" line ".strip())
print("xxhixx".strip("x"))
print("  hi".lstrip())
print("hi  ".rstrip())
print("-".join(["a", "b", "c"]))
print(",".join(("x", "y")))
print("hi".center(6, "*"))
print("hi".ljust(5, "."))
print("hi".rjust(5))
print("42".zfill(5))
print("-42".zfill(5))
print("a\tb".expandtabs(4))
print("key=val".partition("="))
print("a=b=c".rpartition("="))
print("test.py".removeprefix("test."))
print("test.py".removesuffix(".py"))
print("{} and {}".format(1, "two"))
print("{}. {}".format("A", True))
print("abc".isalpha())
print("abc123".isalnum())
print("123".isdigit())
print("   ".isspace())
print("HELLO".isupper())
print("hello".islower())
print("Hello World".istitle())
print("abc".isascii())
print("abc".isidentifier())
print("abc".isprintable())
print("hello"[1:3])
print("hello".replace("l", "L"))
print("aaa".replace("a", "b", 2))
