print("hello from pyluna")
print(1 + 2 * 3)
print(10 / 4)
print(True and False)
print(True or False)
print(not True)
print(True)
print(False)
print(None)
x = 5
print(x)
print("text" + " concat")
print("eq" == "eq")
print(1 != 2)
print(3 > 2)
print(len("hello"))