print(isinstance(5, int))
print(isinstance(5, float))
print(isinstance(5.5, float))
print(isinstance("hi", str))
print(isinstance([1], list))
print(isinstance((1, 2), tuple))
print(isinstance(5, (int, str)))
print(isinstance("hi", (int, str)))
print(isinstance(5, (float, str)))
print(isinstance(True, int))